services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${NGINX_PORT:-82}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
      mailhog:
        condition: service_started

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-billing}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-billing}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "${MAILHOG_PORT:-8025}:8025"

volumes:
  database_data:
