<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260727122600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Billing user, course and transaction tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, balance NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_billing_course_code ON course (code)');
        $this->addSql('CREATE TABLE billing_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, type VARCHAR(20) NOT NULL, amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F70B293DA76ED395 ON billing_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_F70B293D591CC992 ON billing_transaction (course_id)');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F70B293DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F70B293D591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F70B293DA76ED395');
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F70B293D591CC992');
        $this->addSql('DROP TABLE billing_transaction');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE "user"');
    }
}
